CREATE TABLE produtos (
        id INT AUTO_INCREMENT PRIMARY KEY,
            nome_produto VARCHAR(255) NOT NULL,
                preco DECIMAL(10, 2) check(preco>0) NOT NULL,
                    categoria VARCHAR(100),
                        imagem_url VARCHAR(255)
                        );
                        INSERT INTO produtos (nome_produto, preco, categoria, imagem_url) VALUES
                        ('Cerveja Itaipava 600ml', 7.50, 'Fermentadas', 'img/itaipava.jpg'),
                        ('Vinho Tinto Malbec 750ml', 59.90, 'Fermentadas', 'img/vinho.webp'),
                        ('Sidra Cereser 660ml', 15.00, 'Fermentadas', 'img/cereser.jpg'),
                        ('Cerveja Artesanal Baden 600ml', 22.00, 'Fermentadas', 'img/baden.png'),
                        ('Cerveja Pilsen Lata 350ml', 5.50, 'Fermentadas', 'img/pilsen.webp'),
                        ('Vinho Tinto Bordô Suave Góes 750ml', 29.90, 'Fermentadas', 'img/goes.jpg'),
                        ('Casillero Del Diablo Cabernet Sauvignon 750ml', 38.00, 'Fermentadas', 'img/concha.jpg'),
                        ('Cerveja Corona 330ml', 6.79, 'Fermentadas', 'img/corona.webp'),
                        ('Vinho Tinto Suave Pérgola 1L', 23.07, 'Fermentadas', 'img/pergola.jpg'),
                        ('Sidra Bfiver 750ml', 96.00, 'Fermentadas', 'img/bfiver.webp'),
                        ('Vinho Tinto Gato Negro Cabernet Sauvignon 750 Ml', 41.21, 'Fermentadas', 'img/gato.webp'),
                        ('Cerveja Heineken Long Neck 330ml', 6.49, 'Fermentadas', 'img/heineken.webp'),
                        ('Cerveja Spaten 600ml', 8.90, 'Fermentadas', 'img/spaten.webp'),
                        ('Vinho Rosé Piscine 750ml', 95.00, 'Fermentadas', 'img/rose.webp'),
                        ('Espumante Chandon Passion 750ml', 89.90, 'Fermentadas', 'img/chandon.jpg'),
                        ('Cerveja Skol 600ml', 7.90, 'Fermentadas', 'img/skol.jpg'),
                        ('Cerveja Brahma 600ml', 7.50, 'Fermentadas', 'img/brahma.jpg'),
                        ('Vinho Goes Tinto Suave 750ml', 29.90, 'Fermentadas', 'img/goest.webp'),
                        ('Espumante Veuve Clicquot 750ml', 120.00, 'Fermentadas', 'img/veuve.jpg'),
                        ('Cerveja Antarctica 600ml', 7.50, 'Fermentadas', 'img/antarctica.jpg'),
                        ('Cachaça Prata Seleta 1L', 25.00, 'Destiladas', 'img/cachaca.webp'),
                        ('Whisky Ballantines Finest 8 anos 1 Litro', 89.90, 'Destiladas', 'img/whisky.webp'),
                        ('Gin Tônica Ready-to-Drink 269ml', 18.00, 'Destiladas', 'img/gint.avif'),
                        ('Tequila Jose Cuervo Ouro 750ml', 120.00, 'Destiladas', 'img/tequilao.webp'),
                        ('Vodka Smirnoff 1L', 65.00, 'Destiladas', 'img/vodkas.webp'),
                        ('Rum Bacardi', 55.00, 'Destiladas', 'img/rum.jpg'),
                        ('White Horse Whisky 1L', 69.90, 'Destiladas', 'img/white.webp'),
                        ('Absolut Vodka 750Ml', 72.90, 'Destiladas', 'img/absolut.jpg'),
                        ('Gin Tanqueray London Dry, 750ml', 99.97, 'Destiladas', 'img/london.png'),
                        ('Vodka Natasha 900ml', 21.99, 'Destiladas', 'img/natasha.webp'),
                        ('Cachaça Velho Barreiro 910ml', 14.99, 'Destiladas', 'img/velho.webp'),
                        ('Whisky Johnnie Walker Black Label 1L', 159.90, 'Destiladas', 'img/johnnie.webp'),
                        ('Gin Bombay Sapphire 750ml', 105.00, 'Destiladas', 'img/bombay.jpg'),
                        ('Cachaça Cabaré Extra Premium 700ml', 180.00, 'Destiladas', 'img/cabare.webp'),
                        ('Vodka Grey Goose 750ml', 135.00, 'Destiladas', 'img/grey.webp'),
                        ('Rum Havana Club Añejo 7 Años 750ml', 120.00, 'Destiladas', 'img/havana.avif'),
                        ('Whisky Chivas Regal 12 Anos 1L', 149.90, 'Destiladas', 'img/chivas.jpg'),
                        ('Gin Hendrick\'s 750ml', 110.00, 'Destiladas', 'img/ginh.webp'),
                        ('Cachaça Ypióca Ouro 1L', 28.00, 'Destiladas', 'img/ypioca.webp'),
                        ('Vodka Absolut Elyx 750ml', 150.00, 'Destiladas', 'img/elyx.jpg'),
                        ('Licor 43 Chocolate 700ml', 45.00, 'Licorosas', 'img/licor.webp'),
                        ('Vermute Tinto Martini 750ml', 32.50, 'Licorosas', 'img/vermute.jpg'),
                        ('Aperitivo Amargo Campari 900ml', 55.00, 'Licorosas', 'img/aperitivo.webp'),
                        ('Licor de Café e Creme Sheridan\'s 700ml', 160.00, 'Licorosas', 'img/cafe.webp'),
                        ('Ballena Licor Morango com Tequila 750ml', 115.71, 'Licorosas', 'img/ballena.jpg'),
                        ('Aperitivo Aperol 750ml', 59.90, 'Licorosas', 'img/aperol.jpg'),
                        ('Amarula Licor 750ml', 65.00, 'Licorosas', 'img/amarula.jpg'),
                        ('Licor de Chocolate Stock 720ml', 42.70, 'Licorosas', 'img/stock.webp'),
                        ('Aperitivo De Ervas Schluck 750ml', 99.90, 'Licorosas', 'img/ervas.avif'),
                        ('Vermute Dry Schluck 700ml', 95.00, 'Licorosas', 'img/vermuted.webp'),
                        ('Licor Tia Maria 700ml', 144.90, 'Licorosas', 'img/maria.webp'),
                        ('Licor Cointreau 700ml', 125.00, 'Licorosas', 'img/licorc.webp'),
                        ('Licor Amarula Raspberry 750ml', 54.90, 'Licorosas', 'img/amarulac.webp'),
                        ('Licor de Doce de Leite Don Luiz 750ml', 89.00, 'Licorosas', 'img/don.webp'),
                        ('Vinho do Porto Ferreira Tawny 750ml', 79.90, 'Licorosas', 'img/ferreira.jpg'),
                        ('Licor de Maracujá Casa Petro - 500ml', 120.00, 'Licorosas', 'img/maracuja.jpg'),
                        ('Licor de Amêndoas Amaretto Disaronno 750ml', 110.00, 'Licorosas', 'img/disa.webp'),
                        ('Licor de Chocolate e Café Kahlúa 750ml', 130.00, 'Licorosas', 'img/cafel.webp'),
                        ('Licor de Frutas Vermelhas Smirnoff 700ml', 105.00, 'Licorosas', 'img/frutas.jpg'),
                        ('Licor de Laranja e Gin Tanqueray 750ml', 105.00, 'Licorosas', 'img/laranja.jpg'),
                        ('Red Bull Energy Drink 250ml', 12.00, 'Não Alcoólicas', 'img/redbull.webp'),
                        ('Suco Natural Laranja 1,5L', 10.00, 'Não Alcoólicas', 'img/suco.webp'),
                        ('Água Mineral com Gás Crystal 500ml', 3.50, 'Não Alcoólicas', 'img/agua.webp'),
                        ('Gatorade Isotônico 500ml', 5.90, 'Não Alcoólicas', 'img/gatorade.webp'),
                        ('Energético Zero Monster 473ml', 8.99, 'Não Alcoólicas', 'img/monsterzero.webp'),
                        ('Isotônico Powerade 500ml', 4.30, 'Não Alcoólicas', 'img/poweradetropicais.webp'),
                        ('Del Valle Suco Uva 1L', 11.50, 'Não Alcoólicas', 'img/delvalleuva.webp'),
                        ('Energético Baly Melancia', 6.00, 'Não Alcoólicas', 'img/energeticobalymelancia.webp'),
                        ('Ducoco Água de Coco 200ml', 2.65, 'Não Alcoólicas', 'img/ducocoaguacoco.webp'),
                        ('Água Mineral Sem Gás Minalba 510ml', 2.19, 'Não Alcoólicas', 'img/minalbanatural.webp'),
                        ('Energético Reign Melon 473ml', 8.95, 'Não Alcoólicas', 'img/reignmelon.webp'),
                        ('Refrigerante Coca-Cola Original 2L', 9.50, 'Não Alcoólicas', 'img/cocacola.png'),
                        ('Água de Coco Obrigado 1L', 12.90, 'Não Alcoólicas', 'img/aguacocoobrigado.webp'),
                        ('H2OH! Limão 500ml', 4.50, 'Não Alcoólicas', 'img/h2olimao.webp'),
                        ('Suco Prats Laranja 900ml', 14.00, 'Não Alcoólicas', 'img/pratslaranja.webp'),
                        ('Energético Monster Ultra 473ml', 9.99, 'Não Alcoólicas', 'img/monsterultra.jpg'),
                        ('Isotônico Gatorade Laranja 500ml', 5.50, 'Não Alcoólicas', 'img/gatoradelaranja.webp'),
                        ('Água Mineral com Gás Perrier 750ml', 7.90, 'Não Alcoólicas', 'img/perrieragua.webp'),
                        ('Ice Tea Leão, Limão 500ml', 12.00, 'Não Alcoólicas', 'img/chagelado.webp'),
                        ('Nescau 270g', 10.00, 'Não Alcoólicas', 'img/nescau.jpg');

                        SELECT * FROM produtos;
)